<?php
$header='<header id="header" class="header header-wrapper">';
   $header.='<div class="colorz header-top" style=" height: 40px; ">';
      $header.='<div class="container">';
         $header.='<div class="row">';
            $header.='<div class="col-12 col-lg-6 pd8">';
               $header.='<p class="zxs">'.$common->chao_mung.'</p>';
            $header.='</div>';
            $header.='<div class="col-lg-3 hd992 pd8">';
               $formattedPhoneNumber = substr_replace($common->lien_he_sdt, '-', 3, 0);
               $formattedPhoneNumber = substr_replace($formattedPhoneNumber, '-', 7, 0);
               $header.='<p class="zxs tal-r"><span class="icon-phone icon-headrez"></span>Hotline: '.$formattedPhoneNumber.'</p>';
            $header.='</div>';
            $header.='<div class="col-lg-3 hd992 pd8">';
               $header.='<p class="zxs cshv tal-r"><span class="icon-user" style=" margin-right: 5px; "></span>Đăng nhập/Đăng ký</p>';
            $header.='</div>';
         $header.='</div>';
      $header.='</div>';
   $header.='</div>';
   $header.='<div class="header-main" style="background-color: #446CB3;">';
      $header.='<div class="icon-menu" id="menu-mb">';
         $header.='<span class="icon-menumb" style=" font-size: 30px; "></span>';
         $header.='</div>';
         $header.='<div class="icon-cart">';
            $header.='<a href="#" style="text-decoration: none;"><div class="wrap-icon-cart" onclick="show_cart()"><span class="icon-cartx" style=" font-size: 30px; position: relative;"><b class="notify" id="cart-1">0</b></span><span class="gh">Giỏ hàng</span></div></a>';
         $header.='</div>';
         $header.='<div class="container setz">';
            $header.='<div class="row">';
               $header.='<div class="col-12 col-lg-3 brz" style="height: 48px;">';
                  $header.='<div class="logo re"><a href="'.$home_url.'" title="Trang chủ '.$home_name.'"><img src="'.$common->logo_icon.'" class="header-logo-dark" alt="logo '.$home_name.'"></a></div>';
               $header.='</div>';
               $header.='<div class="col-12 col-lg-6 seah">';
                  $header.='<form action='.$home_url.'>';
                     $header.='<div class="input-group">';
                        $header.='<input type="search" name="s" placeholder="Tìm kiếm..." aria-describedby="button-addon5" class="form-control" autocomplete="off">';
                        $header.='<div class="input-group-append">';
                           $header.='<button id="button-addon5" type="submit" class="btn brs" style="background: rgb(255, 152, 0);"> <span class="icon-search" style="font-size: 15px;"></span> </button>';
                        $header.='</div>';
                     $header.='</div>';
                  $header.='</form>';
               $header.='</div>';
            $header.='</div>';
         $header.='</div>';
   $header.='</div>';
   $header.='<div class=" header-bottom">';
      $header.='<div class="container wr-menu ">';
         $header.='<div id="set-menu" class="set-menu hide-menu">';
            $header.='<div class="menu">';
               $header.='<ul>';
                  $header.='<li class="menu-desktop" onclick="toggle_menu_destop()"><span class="icon-menumb" style="font-size: 27px; display: inline-block; width: 28px;"></span></li>';
                        $header.='<li><a href="'.$home_url.'" title="'.$home_name.'">Trang Chủ</a></li>';
                        foreach($common->menu as $x){
                           $header.='<li><a onclick="hide_menu()" href="'.$x->value.'" title="'.$x->name.'">'.$x->name.'</a></li>';
                        }
                  $header.='</ul>';
               $header.='</div>';
               $header.='<div class="dimmer" id="dimmer" onclick="hide_menu()"><span>x</span></div>';
            $header.='</div>';
         $header.='</div>';
   $header.='</div>';
$header.='</header>';
?>